version: '3'

services:
  db:
    image: neo4j:3.4.7
    restart: always
    ports: 
      - 7474:7474
      - 6477:6477
      - 7687:7687
    volumes: 
      - ./db/neo4j/conf:/conf
      - ./db/neo4j/data:/data
      - ./db/neo4j/logs:/logs
      - ./db/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connector_bolt_listen__address=:7687
  app:
    build: .
    command: npm run dev
    ports:
      - 8080:8080
    volumes: 
      - "./service:/home/app/src"
    environment:
      - DB_HOST=db
      - DB_USER=neo4j
      - DB_PASSWORD=test
    depends_on: 
      - db
  
